# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Test and build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Checkout with submodules
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Test
      uses: gradle/gradle-build-action@6095a76664413da4c8c134ee32e8a8ae900f0f1f
      with:
        arguments: test --info

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Checkout with submodules
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Build
      uses: gradle/gradle-build-action@6095a76664413da4c8c134ee32e8a8ae900f0f1f
      with:
        arguments: buildJavaCard --info

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: applet/**/build/javacard/*
